x-zane-env:
  CFRAME_ADMIN_EMAIL: hello@fredkiss.dev
  CFRAME_ADMIN_NAME: fredkisss
  CFRAME_ADMIN_PASSWORD: "{{ generate_password | 8 }}"
  NUXT_SESSION_PASSWORD: "{{ generate_password | 32 }}"
  CF_DOMAIN: "{{ generate_domain }}"

services:
  chronoframe:
    image: ghcr.io/hoshinosuzumi/chronoframe:latest
    container_name: chronoframe
    restart: unless-stopped
    volumes:
      - chronoframe-data:/app/data
    environment:
      # Admin email (required)
      - CFRAME_ADMIN_EMAIL=$CFRAME_ADMIN_EMAIL
      # Admin username (optional, default Chronoframe)
      - CFRAME_ADMIN_NAME=$CFRAME_ADMIN_NAME
      # Admin password (optional, default CF1234@!)
      - CFRAME_ADMIN_PASSWORD=$CFRAME_ADMIN_PASSWORD
      - NUXT_ALLOW_INSECURE_COOKIE=true
      # Site metadata (all optional)
      - NUXT_PUBLIC_APP_TITLE=fred's lib
      - NUXT_PUBLIC_APP_SLOGAN=fun fun fun
      - NUXT_PUBLIC_APP_AUTHOR=fredkisss
      - NUXT_PUBLIC_APP_AVATAR_URL=https://github.com/fredkiss3.png
      # Map provider (maplibre/mapbox)
      - NUXT_PUBLIC_MAP_PROVIDER=maplibre
      # MapTiler access token for MapLibre
      - NUXT_PUBLIC_MAP_MAPLIBRE_TOKEN=bYkKp9UznQZ5h8yHrvkt
      # Storage provider (local)
      - NUXT_STORAGE_PROVIDER=local
      - NUXT_PROVIDER_LOCAL_PATH=/app/data/storage
      # # Session password (32‑char random string, required)
      - NUXT_SESSION_PASSWORD=$NUXT_SESSION_PASSWORD
      # Storage provider (s3)
      # - NUXT_STORAGE_PROVIDER=s3
      # - NUXT_PROVIDER_S3_ENDPOINT=https://rustfs-local.zaneops.dev/
      # - NUXT_PROVIDER_S3_BUCKET=chronoframe
      # - NUXT_PROVIDER_S3_REGION=us-east-1
      # - NUXT_PROVIDER_S3_ACCESS_KEY_ID=4qgGb7Cj03WKhep6cnJy
      # - NUXT_PROVIDER_S3_SECRET_ACCESS_KEY=vsRoqJDVGTlHEfO96mASrk1Czdiycx7hQaWt5wZ0
    deploy:
      labels:
        zane.http.routes.0.port: 3000
        zane.http.routes.0.domain: $CF_DOMAIN
volumes:
  chronoframe-data:
