x-zane-env:
  GRAFANA_DOMAIN: "{{ generate_domain }}"

version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise:9.5.20
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
    deploy:
      labels:
        zane.http.routes.0.port: 3000
        zane.http.routes.0.domain: ${GRAFANA_DOMAIN}
volumes:
  grafana-storage: {}
