x-zane-env:
  main_domain: "{{ generate_domain }}"
  api_domain: "{{ generate_domain }}"
  db_password: "{{ generate_password | 32 }}"
  cookie_secret: "{{ generate_password | 32 }}"
  redis_password: "{{ generate_password | 32 }}"
  SERVICE_FQDN_OPDASHBOARD: http://${main_domain}
  SERVICE_FQDN_OPAPI: http://${api_domain}
  OPENPANEL_POSTGRES_DB: openpanel-db
  SERVICE_USER_POSTGRES: openpanel
  SERVICE_PASSWORD_POSTGRES: ${db_password}
  SERVICE_PASSWORD_REDIS: ${redis_password}
  SERVICE_BASE64_COOKIESECRET: ${cookie_secret}
  OP_WORKER_REPLICAS: "1"
  RESEND_API_KEY: ""
  OPENPANEL_ALLOW_REGISTRATION: "true"
  OPENPANEL_ALLOW_INVITATION: "true"
  OPENPANEL_VERSION: 1.2.2
  OP_DASHBOARD_VERSION: $OPENPANEL_VERSION
  OP_API_VERSION: $OPENPANEL_VERSION
  OP_WORKER_VERSION: $OPENPANEL_VERSION

services:
  op-db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - type: volume
        target: /var/lib/postgresql/data
        source: op-db-data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=${OPENPANEL_POSTGRES_DB}
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
  op-kv:
    image: redis:7.2.5-alpine
    restart: always
    volumes:
      - type: volume
        target: /data
        source: op-kv-data
    command:
      redis-server --requirepass ${SERVICE_PASSWORD_REDIS} --maxmemory-policy
      noeviction
    healthcheck:
      test:
        - CMD
        - redis-cli
        - -a
        - ${SERVICE_PASSWORD_REDIS}
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
  op-ch:
    image: clickhouse/clickhouse-server:25.10.2.65
    restart: always
    volumes:
      - type: volume
        target: /var/lib/clickhouse
        source: op-ch-data
      - type: volume
        target: /var/log/clickhouse-server
        source: op-ch-logs
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    healthcheck:
      test: ["CMD-SHELL", 'clickhouse-client --query "SELECT 1"']
      interval: 10s
      timeout: 5s
      retries: 5
    configs:
      - source: clickhouse-config.xml
        target: /etc/clickhouse-server/config.d/op-config.xml
      - source: clickhouse-user-config.xml
        target: /etc/clickhouse-server/users.d/op-user-config.xml
      - source: init-db.sql
        target: /docker-entrypoint-initdb.d/1_init-db.sql
  op-api:
    image: lindesvard/openpanel-api:${OP_API_VERSION:-latest}
    restart: always
    command:
      "sh -c \"\n  echo 'Waiting for PostgreSQL to be ready...'\n  while !\
      \ nc -z op-db 5432; do\n    sleep 1\n  done\n  echo 'PostgreSQL is ready'\n\n\
      \  echo 'Waiting for ClickHouse to be ready...'\n  while ! nc -z op-ch 8123;\
      \ do\n    sleep 1\n  done\n  echo 'ClickHouse is ready'\n\n  echo 'Running migrations...'\n\
      \  \n  echo '$DATABASE_URL'\n\n  CI=true pnpm -r run migrate:deploy\n\n  pnpm\
      \ start\n\"\n"
    environment:
      DATABASE_URL: postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@op-db:5432/${OPENPANEL_POSTGRES_DB}?schema=public
      DATABASE_URL_DIRECT: postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@op-db:5432/${OPENPANEL_POSTGRES_DB}?schema=public
      REDIS_URL: redis://default:${SERVICE_PASSWORD_REDIS}@op-kv:6379
      CLICKHOUSE_URL: ${OPENPANEL_CLICKHOUSE_URL:-http://op-ch:8123/openpanel}
      NODE_ENV: production
      NEXT_PUBLIC_SELF_HOSTED: "true"
      VITE_PUBLIC_SELF_HOSTED: "true"
      SERVICE_FQDN_OPAPI: /api
      NEXT_PUBLIC_API_URL: $SERVICE_FQDN_OPAPI
      NEXT_PUBLIC_DASHBOARD_URL: $SERVICE_FQDN_OPDASHBOARD
      COOKIE_SECRET: ${SERVICE_BASE64_COOKIESECRET}
      ALLOW_REGISTRATION: ${OPENPANEL_ALLOW_REGISTRATION:-false}
      ALLOW_INVITATION: ${OPENPANEL_ALLOW_INVITATION:-true}
      EMAIL_SENDER: ${OPENPANEL_EMAIL_SENDER}
      RESEND_API_KEY: ${RESEND_API_KEY}
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:3000/healthcheck || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - op-db
      - op-ch
      - op-kv
    ports: []
    deploy:
      labels:
        zane.http.routes.0.domain: ${api_domain}
        zane.http.routes.0.base_path: /
        zane.http.routes.0.port: 3000
        zane.http.routes.0.strip_prefix: "false"
    volumes: []
  op-dashboard:
    image: lindesvard/openpanel-dashboard:${OP_DASHBOARD_VERSION:-latest}
    restart: always
    depends_on:
      - op-api
    environment:
      DATABASE_URL: postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@op-db:5432/${OPENPANEL_POSTGRES_DB}?schema=public
      DATABASE_URL_DIRECT: postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@op-db:5432/${OPENPANEL_POSTGRES_DB}?schema=public
      REDIS_URL: redis://default:${SERVICE_PASSWORD_REDIS}@op-kv:6379
      CLICKHOUSE_URL: ${OPENPANEL_CLICKHOUSE_URL:-http://op-ch:8123/openpanel}
      NODE_ENV: production
      NEXT_PUBLIC_SELF_HOSTED: "true"
      VITE_PUBLIC_SELF_HOSTED: "true"
      SERVICE_FQDN_OPDASHBOARD:
      NEXT_PUBLIC_API_URL: $SERVICE_FQDN_OPAPI
      NEXT_PUBLIC_DASHBOARD_URL: $SERVICE_FQDN_OPDASHBOARD
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:3000/api/healthcheck || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    ports: []
    deploy:
      labels:
        zane.http.routes.0.domain: ${main_domain}
        zane.http.routes.0.base_path: /
        zane.http.routes.0.port: 3000
        zane.http.routes.0.strip_prefix: "false"
    volumes: []
  op-worker:
    image: lindesvard/openpanel-worker:${OP_WORKER_VERSION:-latest}
    restart: always
    depends_on:
      - op-api
    environment:
      DATABASE_URL: postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@op-db:5432/${OPENPANEL_POSTGRES_DB}?schema=public
      DATABASE_URL_DIRECT: postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@op-db:5432/${OPENPANEL_POSTGRES_DB}?schema=public
      REDIS_URL: redis://default:${SERVICE_PASSWORD_REDIS}@op-kv:6379
      CLICKHOUSE_URL: ${OPENPANEL_CLICKHOUSE_URL:-http://op-ch:8123/openpanel}
      SERVICE_FQDN_OPBULLBOARD:
      NODE_ENV=production:
      NEXT_PUBLIC_SELF_HOSTED: "true"
      VITE_PUBLIC_SELF_HOSTED: "true"
      NEXT_PUBLIC_API_URL: $SERVICE_FQDN_OPAPI
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:3000/healthcheck || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
    volumes: []
x-database:
  DATABASE_URL: postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@op-db:5432/${OPENPANEL_POSTGRES_DB}?schema=public
  DATABASE_URL_DIRECT: postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@op-db:5432/${OPENPANEL_POSTGRES_DB}?schema=public
  REDIS_URL: redis://default:${SERVICE_PASSWORD_REDIS}@op-kv:6379
  CLICKHOUSE_URL: ${OPENPANEL_CLICKHOUSE_URL:-http://op-ch:8123/openpanel}
volumes:
  op-db-data:
  op-kv-data:
  op-ch-data:
  op-ch-logs:
  op-proxy-data:
  op-proxy-config:
configs:
  clickhouse-config.xml:
    content:
      "    <clickhouse>\n        <logger>\n            <level>warning</level>\n\
      \            <console>true</console>\n        </logger>\n        <keep_alive_timeout>10</keep_alive_timeout>\n\
      \        <!-- Stop all the unnecessary logging -->\n        <query_thread_log\
      \ remove=\"remove\"/>\n        <query_log remove=\"remove\"/>\n        <text_log\
      \ remove=\"remove\"/>\n        <trace_log remove=\"remove\"/>\n        <metric_log\
      \ remove=\"remove\"/>\n        <asynchronous_metric_log remove=\"remove\"/>\n\
      \        <session_log remove=\"remove\"/>\n        <part_log remove=\"remove\"\
      />\n        <listen_host>0.0.0.0</listen_host>\n        <interserver_listen_host>0.0.0.0</interserver_listen_host>\n\
      \        <interserver_http_host>opch</interserver_http_host>\n        <!-- Disable\
      \ cgroup memory observer -->\n        <cgroups_memory_usage_observer_wait_time>0</cgroups_memory_usage_observer_wait_time>\n\
      \        <!-- Not used anymore, but kept for backwards compatibility -->\n \
      \       <macros>\n            <shard>1</shard>\n            <replica>replica1</replica>\n\
      \            <cluster>openpanel_cluster</cluster>\n        </macros>\n    </clickhouse>\n"
  clickhouse-user-config.xml:
    content:
      "    <clickhouse>\n        <profiles>\n        <default>\n          \
      \  <log_queries>0</log_queries>\n            <log_query_threads>0</log_query_threads>\n\
      \        </default>\n    </profiles>\n    </clickhouse>\n"
  init-db.sql:
    content: "CREATE DATABASE IF NOT EXISTS openpanel;

      "
