x-zane-env:
  main_domain: "{{ generate_domain }}"
  DOMAIN_NAME: ${main_domain}
services:
  penpot-frontend:
    image: penpotapp/frontend:2.6.1
    restart: always
    volumes:
      - type: volume
        target: /opt/data/assets
        source: penpot_assets
    depends_on:
      - penpot-backend
      - penpot-exporter
    environment:
      PENPOT_FLAGS: disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies
    deploy:
      labels:
        zane.http.routes.0.domain: ${main_domain}
        zane.http.routes.0.base_path: /
        zane.http.routes.0.port: 8080
        zane.http.routes.0.strip_prefix: "false"
  penpot-backend:
    image: penpotapp/backend:2.6.1
    restart: always
    volumes:
      - type: volume
        target: /opt/data/assets
        source: penpot_assets
    depends_on:
      - penpot-postgres
      - penpot-redis
    environment:
      PENPOT_PUBLIC_URI: http://${DOMAIN_NAME}
      PENPOT_FLAGS: disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies
      PENPOT_DATABASE_URI: postgresql://penpot-postgres/penpot
      PENPOT_DATABASE_USERNAME: penpot
      PENPOT_DATABASE_PASSWORD: penpot
      PENPOT_REDIS_URI: redis://penpot-redis/0
      PENPOT_ASSETS_STORAGE_BACKEND: assets-fs
      PENPOT_STORAGE_ASSETS_FS_DIRECTORY: /opt/data/assets
      PENPOT_TELEMETRY_ENABLED: true
      PENPOT_SMTP_DEFAULT_FROM: no-reply@example.com
      PENPOT_SMTP_DEFAULT_REPLY_TO: no-reply@example.com
      PENPOT_SMTP_HOST: penpot-mailcatch
      PENPOT_SMTP_PORT: 1025
      PENPOT_SMTP_USERNAME: null
      PENPOT_SMTP_PASSWORD: null
      PENPOT_SMTP_TLS: false
      PENPOT_SMTP_SSL: false
  penpot-exporter:
    image: penpotapp/exporter:2.6.1
    restart: always
    environment:
      PENPOT_PUBLIC_URI: http://penpot-frontend
      PENPOT_REDIS_URI: redis://penpot-redis/0
  penpot-postgres:
    image: postgres:15
    restart: always
    stop_signal: SIGINT
    volumes:
      - type: volume
        target: /var/lib/postgresql/data
        source: penpot_postgres_v15
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot
  penpot-redis:
    image: redis:7.2
    restart: always
  penpot-mailcatch:
    image: sj26/mailcatcher:latest
    restart: always
volumes:
  penpot_postgres_v15: null
  penpot_assets: null
  penpot_traefik: null
