x-zane-env:
  RUSTFS_DOMAIN: "{{ generate_domain }}"
  RUSTFS_API_DOMAIN: "{{ generate_domain }}"
  RUSTFS_ACCESS_KEY: rustfs
  RUSTFS_SECRET_KEY: "{{ generate_password | 32 }}"

services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    deploy:
      labels:
        zane.http.routes.0.port: 9001
        zane.http.routes.0.domain: $RUSTFS_DOMAIN
        zane.http.routes.1.port: 9000
        zane.http.routes.1.domain: $RUSTFS_API_DOMAIN
    environment:
      - RUSTFS_VOLUMES=/data
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_ACCESS_KEY=$RUSTFS_ACCESS_KEY
      - RUSTFS_SECRET_KEY=$RUSTFS_SECRET_KEY
      - RUSTFS_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
    volumes:
      - rustfs-data:/data
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:9000/health && curl -f http://localhost:9001/rustfs/console/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  rustfs-data:
