version: "3.8"
x-zane-env:
  valkey_password: "{{ generate_password | 32 }}"
  VALKEY_PASSWORD: ${valkey_password}
services:
  valkey:
    image: valkey/valkey:8.1.4
    restart: unless-stopped
    configs:
      - source: valkey.conf
        target: /etc/valkey/valkey.conf
    volumes:
      # - ../files/valkey.conf:/etc/valkey/valkey.conf
      - valkey-data:/data
    command: valkey-server /etc/valkey/valkey.conf
    environment:
      - VALKEY_PASSWORD=${VALKEY_PASSWORD}
    healthcheck:
      test:
        - CMD-SHELL
        - valkey-cli -a "$$VALKEY_PASSWORD" ping | grep PONG
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
volumes:
  valkey-data: {}
configs:
  valkey.conf:
    content: |
      # Valkey configuration file
      # For more information, see: https://github.com/valkey-io/valkey

      # Network
      bind 0.0.0.0
      port 6379
      protected-mode yes

      # General
      daemonize no
      supervised no
      pidfile /data/valkey.pid
      loglevel notice
      logfile ""

      # Snapshotting
      save 900 1
      save 300 10
      save 60 10000
      stop-writes-on-bgsave-error yes
      rdbcompression yes
      rdbchecksum yes
      dbfilename dump.rdb
      dir /data

      # Replication
      replica-serve-stale-data yes
      replica-read-only yes

      # Security
      requirepass ${valkey_password}

      # Memory management
      maxmemory-policy noeviction

      # Append only file
      appendonly yes
      appendfilename "appendonly.aof"
      appendfsync everysec
      no-appendfsync-on-rewrite no
      auto-aof-rewrite-percentage 100
      auto-aof-rewrite-min-size 64mb
