x-zane-env:
  OLLAMA_IMAGE_VERSION: latest
services:
  ollama:
    image: ollama/ollama:${OLLAMA_IMAGE_VERSION:-latest}
    volumes:
      - ollama:/root/.ollama
    # --------------------------------------------------------------------------
    # Optional: GPU Support (Uncomment the following lines to enable)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # --------------------------------------------------------------------------

volumes:
  ollama:
