version: "3.8"
x-zane-env:
  main_domain: "{{ generate_domain }}"
  minio_api_domain: "{{ generate_domain }}"
  minio_console_domain: "{{ generate_domain }}"
  mysql_database: planetscale
  mysql_user: root
  cap_aws_bucket: capso
  cap_aws_region: us-east-1
  DOMAIN: ${main_domain}
  MYSQL_DATABASE: ${mysql_database}
  MYSQL_USER: ${mysql_user}
  MYSQL_PASSWORD: "{{ generate_password | 32 }}"
  MYSQL_ROOT_PASSWORD: "{{ generate_password | 32 }}"
  DATABASE_ENCRYPTION_KEY: "{{ generate_password | 32 }}"
  NEXTAUTH_SECRET: "{{ generate_password | 32 }}"
  CAP_AWS_ACCESS_KEY: "{{ generate_password | 16 }}"
  CAP_AWS_SECRET_KEY: "{{ generate_password | 16 }}"
  CAP_AWS_BUCKET: ${cap_aws_bucket}
  CAP_AWS_REGION: ${cap_aws_region}
  MINIO_ROOT_USER: "{{ generate_password | 16 }}"
  MINIO_ROOT_PASSWORD: "{{ generate_password | 16 }}"
  MEDIA_SERVER_WEBHOOK_SECRET: "{{ generate_password | 32 }}"

services:
  cap-web:
    image: ghcr.io/capsoftware/cap-web:latest
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@ps-mysql:3306/${MYSQL_DATABASE}?ssl={"rejectUnauthorized":false}
      WEB_URL: http://${DOMAIN}:3000
      NEXTAUTH_URL: http://${DOMAIN}:3000
      DATABASE_ENCRYPTION_KEY: ${DATABASE_ENCRYPTION_KEY}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      CAP_AWS_ACCESS_KEY: ${CAP_AWS_ACCESS_KEY}
      CAP_AWS_SECRET_KEY: ${CAP_AWS_SECRET_KEY}
      CAP_AWS_BUCKET: ${CAP_AWS_BUCKET}
      CAP_AWS_REGION: ${CAP_AWS_REGION}
      S3_PUBLIC_ENDPOINT: http://${DOMAIN}:3902
      S3_INTERNAL_ENDPOINT: http://minio:3902
      MEDIA_SERVER_URL: http://media-server:3456
      MEDIA_SERVER_WEBHOOK_SECRET: ${MEDIA_SERVER_WEBHOOK_SECRET}
      MEDIA_SERVER_WEBHOOK_URL: http://cap-web:3000
    depends_on:
      - ps-mysql
      - minio
    deploy:
      labels:
        zane.http.routes.0.domain: ${main_domain}
        zane.http.routes.0.base_path: /
        zane.http.routes.0.port: 3000
        zane.http.routes.0.strip_prefix: "false"

  media-server:
    image: ghcr.io/capsoftware/cap-media-server:latest
    restart: unless-stopped
    environment:
      PORT: 3456
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3456/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  ps-mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    command:
      - --max_connections=1000
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - type: volume
        target: /var/lib/mysql
        source: ps-mysql
  minio:
    image: quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
    command: server /bitnami/minio/data --address ":3902" --console-address ":3903"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - type: volume
        target: /bitnami/minio/data
        source: minio-data
      - type: volume
        target: /certs
        source: minio-certs
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:3902/minio/health/ready
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      labels:
        zane.http.routes.0.domain: ${minio_api_domain}
        zane.http.routes.0.base_path: /
        zane.http.routes.0.port: 3902
        zane.http.routes.0.strip_prefix: "false"
        zane.http.routes.1.domain: ${minio_console_domain}
        zane.http.routes.1.base_path: /
        zane.http.routes.1.port: 3903
        zane.http.routes.1.strip_prefix: "false"
volumes:
  ps-mysql:
    driver: local
  minio-data:
    driver: local
  minio-certs:
    driver: local
