x-zane-env:
  CFRAME_ADMIN_EMAIL: "{{ generate_email }}"
  CFRAME_ADMIN_NAME: "{{ generate_username }}"
  CFRAME_ADMIN_PASSWORD: "{{ generate_password | 8 }}"
  NUXT_SESSION_PASSWORD: "{{ generate_password | 32 }}"
  CF_DOMAIN: "{{ generate_domain }}"

services:
  chronoframe:
    image: ghcr.io/hoshinosuzumi/chronoframe:latest
    container_name: chronoframe
    restart: unless-stopped
    volumes:
      - chronoframe-data:/app/data
    environment:
      # Admin email (required)
      - CFRAME_ADMIN_EMAIL=${CFRAME_ADMIN_EMAIL}
      # Admin username (optional, default Chronoframe)
      - CFRAME_ADMIN_NAME=${CFRAME_ADMIN_NAME}
      # Admin password (optional, default CF1234@!)
      - CFRAME_ADMIN_PASSWORD=${CFRAME_ADMIN_PASSWORD}
      # Allow access via HTTP: ONLY LOCALLY !!
      # - NUXT_ALLOW_INSECURE_COOKIE=true
      # Site metadata (all optional)
      - NUXT_PUBLIC_APP_TITLE
      - NUXT_PUBLIC_APP_SLOGAN
      - NUXT_PUBLIC_APP_AUTHOR
      - NUXT_PUBLIC_APP_AVATAR_URL
      # Map provider (maplibre/mapbox)
      - NUXT_PUBLIC_MAP_PROVIDER=maplibre
      # MapTiler access token for MapLibre, how to get a key: https://cloud.maptiler.com/account/keys/
      - NUXT_PUBLIC_MAP_MAPLIBRE_TOKEN
      # ChronoFrame comes with built-in light and dark styles that switch automatically.
      # If you configure a custom style, it will override the default styles.
      # Example: https://demotiles.maplibre.org/globe.json
      - NUXT_PUBLIC_MAP_MAPLIBRE_STYLE
      # To use Mapbox as the map provider, how to get a key:  https://console.mapbox.com/account/access-tokens/
      - NUXT_PUBLIC_MAPBOX_ACCESS_TOKEN
      # If you configure a custom style, it will override the default styles.
      # Example: mapbox://styles/mapbox/streets-v11
      - NUXT_PUBLIC_MAP_MAPBOX_STYLE
      # Storage provider (local)
      - NUXT_STORAGE_PROVIDER=local
      - NUXT_PROVIDER_LOCAL_PATH=/app/data/storage
      # # Session password (32‑char random string, required)
      - NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}
      # Storage provider (s3)
      # - NUXT_STORAGE_PROVIDER=s3
      # - NUXT_PROVIDER_S3_ENDPOINT
      # - NUXT_PROVIDER_S3_BUCKET
      # - NUXT_PROVIDER_S3_REGION=us-east-1
      # - NUXT_PROVIDER_S3_ACCESS_KEY_ID
      # - NUXT_PROVIDER_S3_SECRET_ACCESS_KEY
    deploy:
      labels:
        zane.http.routes.0.port: 3000
        zane.http.routes.0.domain: ${CF_DOMAIN}
volumes:
  chronoframe-data:
