x-zane-env:
  dashboard_domain: "{{ generate_domain }}"
  backend_domain: "{{ generate_domain }}"
  actions_domain: "{{ generate_domain }}"
  NEXT_PUBLIC_DEPLOYMENT_URL: http://${backend_domain}
  CONVEX_CLOUD_ORIGIN: http://${backend_domain}
  CONVEX_SITE_ORIGIN: http://${actions_domain}
  INSTANCE_NAME: "{{ generate_slug }}"

services:
  backend:
    # Change this to :${REV} if you want to pin to a specific version
    image: ghcr.io/get-convex/convex-backend:latest
    stop_grace_period: 10s
    stop_signal: SIGINT
    volumes:
      - data:/convex/data
    environment:
      - ACTIONS_USER_TIMEOUT_SECS
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - AWS_S3_DISABLE_CHECKSUMS
      - AWS_S3_DISABLE_SSE
      - AWS_S3_FORCE_PATH_STYLE
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - CONVEX_CLOUD_ORIGIN=${CONVEX_CLOUD_ORIGIN:-http://127.0.0.1:${PORT:-3210}}
      - CONVEX_RELEASE_VERSION_DEV
      - CONVEX_SITE_ORIGIN=${CONVEX_SITE_ORIGIN:-http://127.0.0.1:${SITE_PROXY_PORT:-3211}}
      - INSTANCE_NAME=${INSTANCE_NAME}
      - DATABASE_URL
      - DISABLE_BEACON
      - DOCUMENT_RETENTION_DELAY=${DOCUMENT_RETENTION_DELAY:-172800} # Lower default document retention to 2 days
      - DO_NOT_REQUIRE_SSL
      - HTTP_SERVER_TIMEOUT_SECONDS
      - INSTANCE_SECRET
      - MYSQL_URL
      - POSTGRES_URL
      - REDACT_LOGS_TO_CLIENT
      - RUST_BACKTRACE
      - RUST_LOG=${RUST_LOG:-info}
      - S3_ENDPOINT_URL
      - S3_STORAGE_EXPORTS_BUCKET
      - S3_STORAGE_FILES_BUCKET
      - S3_STORAGE_MODULES_BUCKET
      - S3_STORAGE_SEARCH_BUCKET
      - S3_STORAGE_SNAPSHOT_IMPORTS_BUCKET

    healthcheck:
      test: curl -f http://localhost:3210/version
      interval: 5s
      start_period: 10s
    deploy:
      replicas: 0
      labels:
        zane.http.routes.0.domain: ${backend_domain}
        zane.http.routes.0.base_path: /
        zane.http.routes.0.port: 3210
        zane.http.routes.0.strip_prefix: "false"
        zane.http.routes.1.domain: ${actions_domain}
        zane.http.routes.1.base_path: /
        zane.http.routes.1.port: 3211
        zane.http.routes.1.strip_prefix: "false"

  dashboard:
    # Change this to :${REV} if you want to pin to a specific version
    image: ghcr.io/get-convex/convex-dashboard:latest
    stop_grace_period: 10s
    stop_signal: SIGINT
    environment:
      - NEXT_PUBLIC_DEPLOYMENT_URL=${NEXT_PUBLIC_DEPLOYMENT_URL:-http://127.0.0.1:${PORT:-3210}}
      - NEXT_PUBLIC_LOAD_MONACO_INTERNALLY
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      replicas: 0
      labels:
        zane.http.routes.0.domain: ${dashboard_domain}
        zane.http.routes.0.base_path: /
        zane.http.routes.0.port: 6791
        zane.http.routes.0.strip_prefix: "false"
volumes:
  data:
