x-zane-env:
  # issue with `main_domain`: if your `ROOT_DOMAIN` is `127.0.0.1.sslip.io` or `127-0-0-1.sslip.io`, please
  # manually change this domain value to for ex, the IP address of your machine in your local network or use
  # a custom domain, ref: https://github.com/Openpanel-dev/openpanel/issues/272#issuecomment-3765763485
  main_domain: "{{ generate_domain }}"
  cookie_secret: "{{ generate_password | 32 }}"
  db_password: "{{ generate_password | 32 }}"
  redis_password: "{{ generate_password | 32 }}"

  OPENPANEL_VERSION: 2.0.1-rc

  DASHBOARD_URL: "http://${main_domain}"
  API_URL: "http://${main_domain}/api"

  # Database configuration
  POSTGRES_DB: "openpanel"
  POSTGRES_USER: "openpanel"
  POSTGRES_PASSWORD: "${db_password}"
  REDIS_PASSWORD: "${redis_password}"

  # Security
  COOKIE_SECRET: "${cookie_secret}"

  # Registration settings
  ALLOW_REGISTRATION: "true"
  ALLOW_INVITATION: "true"

  # Email configuration (optional - configure for email notifications)
  EMAIL_SENDER: ""
  RESEND_API_KEY: ""

x-common: &x-common
  NODE_ENV: production
  SELF_HOSTED: "true"
  API_URL: ${API_URL}
  DASHBOARD_URL: ${DASHBOARD_URL}
  DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@op-db:5432/${POSTGRES_DB}?schema=public
  DATABASE_URL_DIRECT: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@op-db:5432/${POSTGRES_DB}?schema=public
  REDIS_URL: redis://default:${REDIS_PASSWORD}@op-kv:6379
  CLICKHOUSE_URL: http://op-ch:8123/openpanel
  APP_VERSION: 2.0.1-rc
  ALLOW_REGISTRATION: "false"
  BATCH_SIZE: 5000

services:
  op-db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - op-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  op-kv:
    image: redis:7.2.5-alpine
    restart: always
    volumes:
      - op-redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory-policy noeviction
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  op-ch:
    image: clickhouse/clickhouse-server:25.10.2.65
    restart: always
    volumes:
      - op-ch-data:/var/lib/clickhouse
      - op-ch-logs:/var/log/clickhouse-server
    configs:
      - source: clickhouse-config.xml
        target: /etc/clickhouse-server/config.d/op-config.xml
      - source: clickhouse-user-config.xml
        target: /etc/clickhouse-server/users.d/op-user-config.xml
      - source: init-db.sql
        target: /docker-entrypoint-initdb.d/1_init-db.sql
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    healthcheck:
      test: ["CMD-SHELL", 'clickhouse-client --query "SELECT 1" -d openpanel']
      interval: 10s
      timeout: 5s
      retries: 5

  op-api:
    image: lindesvard/openpanel-api:${OPENPANEL_VERSION:-2.0.0}
    restart: always
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL to be ready...'
        while ! nc -z op-db 5432; do
          sleep 1
        done
        echo 'PostgreSQL is ready'

        echo 'Waiting for ClickHouse to be ready...'
        while ! nc -z op-ch 8123; do
          sleep 1
        done
        echo 'ClickHouse is ready'

        echo 'Running migrations...'

        CI=true pnpm -r run migrate:deploy

        pnpm start
      "
    environment:
      COOKIE_SECRET: ${COOKIE_SECRET}
      ALLOW_REGISTRATION: ${ALLOW_REGISTRATION}
      ALLOW_INVITATION: ${ALLOW_INVITATION}
      EMAIL_SENDER: ${EMAIL_SENDER}
      RESEND_API_KEY: ${RESEND_API_KEY}
      <<: *x-common
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      op-db:
        condition: service_healthy
      op-ch:
        condition: service_healthy
      op-kv:
        condition: service_healthy
    deploy:
      labels:
        zane.http.routes.0.domain: ${main_domain}
        zane.http.routes.0.base_path: /api
        zane.http.routes.0.port: 3000

  op-dashboard:
    image: lindesvard/openpanel-dashboard:${OPENPANEL_VERSION:-2.0.0}
    restart: always
    depends_on:
      op-api:
        condition: service_healthy
    environment:
      <<: *x-common
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:3000/api/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      labels:
        zane.http.routes.0.domain: ${main_domain}
        zane.http.routes.0.port: 3000

  op-worker:
    image: lindesvard/openpanel-worker:${OPENPANEL_VERSION:-2.0.0}
    restart: always
    depends_on:
      op-api:
        condition: service_healthy
    environment:
      <<: *x-common
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  op-db-data:
  op-redis-data:
  op-ch-data:
  op-ch-logs:

configs:
  clickhouse-config.xml:
    content: |
      <clickhouse>
          <logger>
              <level>warning</level>
              <console>true</console>
          </logger>
          <keep_alive_timeout>10</keep_alive_timeout>
          <!-- Stop all the unnecessary logging -->
          <query_thread_log remove="remove"/>
          <query_log remove="remove"/>
          <text_log remove="remove"/>
          <trace_log remove="remove"/>
          <metric_log remove="remove"/>
          <asynchronous_metric_log remove="remove"/>
          <session_log remove="remove"/>
          <part_log remove="remove"/>
          <listen_host>0.0.0.0</listen_host>
          <interserver_listen_host>0.0.0.0</interserver_listen_host>
          <interserver_http_host>opch</interserver_http_host>
          <!-- Disable cgroup memory observer -->
          <cgroups_memory_usage_observer_wait_time>0</cgroups_memory_usage_observer_wait_time>
          <!-- Not used anymore, but kept for backwards compatibility -->
          <macros>
              <shard>1</shard>
              <replica>replica1</replica>
              <cluster>openpanel_cluster</cluster>
          </macros>
      </clickhouse>

  clickhouse-user-config.xml:
    content: |
      <clickhouse>
          <profiles>
              <default>
                  <log_queries>0</log_queries>
                  <log_query_threads>0</log_query_threads>
              </default>
          </profiles>
      </clickhouse>

  init-db.sql:
    content: |
      CREATE DATABASE IF NOT EXISTS openpanel;
