x-zane-env:
  # select a revision to deploy, available values: stable, beta, canary
  AFFINE_REVISION: stable
  main_domain: "{{ generate_domain }}"
  DB_USERNAME: affine
  DB_PASSWORD: "{{ generate_password | 32 }}"
  DB_DATABASE: affine

x-affine-env: &x-common
  AFFINE_REVISION: ${AFFINE_REVISION}

  # set https in production
  # AFFINE_SERVER_HTTPS: true
  # AFFINE_SERVER_HOST: "${main_domain}"
  # or
  # AFFINE_SERVER_EXTERNAL_URL: http://${main_domain}
  PORT: 3010

  # database credentials
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_DATABASE: ${DB_DATABASE}
  REDIS_SERVER_HOST: redis
  DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE:-affine}
  AFFINE_INDEXER_ENABLED: false

services:
  affine:
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    deploy:
      labels:
        zane.http.routes.0.domain: ${main_domain}
        zane.http.routes.0.port: 3010
    depends_on:
      - redis
      - postgres
      - affine_migration
    volumes:
      # custom configurations
      - upload-files:/root/.affine/storage
      - config-files:/root/.affine/config
    environment:
      <<: *x-common

  affine_migration:
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    volumes:
      # custom configurations
      - upload-files:/root/.affine/storage
      - config-files:/root/.affine/config
    command: ["sh", "-c", "node ./scripts/self-host-predeploy.js"]
    environment:
      <<: *x-common
    depends_on:
      - postgres
      - redis
    deploy:
      mode: replicated-job
      restart_policy:
        condition: on-failure

  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: pgvector/pgvector:pg16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE:-affine}
      POSTGRES_INITDB_ARGS: "--data-checksums"
      # you better set a password for you database
      # or you may add 'POSTGRES_HOST_AUTH_METHOD=trust' to ignore postgres security policy
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${DB_USERNAME}",
          "-d",
          "${DB_DATABASE:-affine}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  upload-files:
  config-files:
